env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {
  "no-irregular-whitespace": 1,
  "no-empty": 1,
  "no-useless-escape": 1,
  "no-undef": 1
}
